/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplateIndexRouteImport } from './routes/template/index'
import { Route as Day10IndexRouteImport } from './routes/day-10/index'
import { Route as Day09IndexRouteImport } from './routes/day-09/index'
import { Route as Day04IndexRouteImport } from './routes/day-04/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplateIndexRoute = TemplateIndexRouteImport.update({
  id: '/template/',
  path: '/template/',
  getParentRoute: () => rootRouteImport,
} as any)
const Day10IndexRoute = Day10IndexRouteImport.update({
  id: '/day-10/',
  path: '/day-10/',
  getParentRoute: () => rootRouteImport,
} as any)
const Day09IndexRoute = Day09IndexRouteImport.update({
  id: '/day-09/',
  path: '/day-09/',
  getParentRoute: () => rootRouteImport,
} as any)
const Day04IndexRoute = Day04IndexRouteImport.update({
  id: '/day-04/',
  path: '/day-04/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/day-04': typeof Day04IndexRoute
  '/day-09': typeof Day09IndexRoute
  '/day-10': typeof Day10IndexRoute
  '/template': typeof TemplateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/day-04': typeof Day04IndexRoute
  '/day-09': typeof Day09IndexRoute
  '/day-10': typeof Day10IndexRoute
  '/template': typeof TemplateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/day-04/': typeof Day04IndexRoute
  '/day-09/': typeof Day09IndexRoute
  '/day-10/': typeof Day10IndexRoute
  '/template/': typeof TemplateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/day-04' | '/day-09' | '/day-10' | '/template'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/day-04' | '/day-09' | '/day-10' | '/template'
  id: '__root__' | '/' | '/day-04/' | '/day-09/' | '/day-10/' | '/template/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Day04IndexRoute: typeof Day04IndexRoute
  Day09IndexRoute: typeof Day09IndexRoute
  Day10IndexRoute: typeof Day10IndexRoute
  TemplateIndexRoute: typeof TemplateIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/template/': {
      id: '/template/'
      path: '/template'
      fullPath: '/template'
      preLoaderRoute: typeof TemplateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/day-10/': {
      id: '/day-10/'
      path: '/day-10'
      fullPath: '/day-10'
      preLoaderRoute: typeof Day10IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/day-09/': {
      id: '/day-09/'
      path: '/day-09'
      fullPath: '/day-09'
      preLoaderRoute: typeof Day09IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/day-04/': {
      id: '/day-04/'
      path: '/day-04'
      fullPath: '/day-04'
      preLoaderRoute: typeof Day04IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Day04IndexRoute: Day04IndexRoute,
  Day09IndexRoute: Day09IndexRoute,
  Day10IndexRoute: Day10IndexRoute,
  TemplateIndexRoute: TemplateIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
